//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Dialogus"",
            ""id"": ""b6c3b57b-e183-4120-bcd7-57923695e330"",
            ""actions"": [
                {
                    ""name"": ""NextPhrase"",
                    ""type"": ""Button"",
                    ""id"": ""ecf9d4b4-1341-456b-8cde-8382c1c5b87b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8466ac91-74fa-4837-90a1-dee7295e64c9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextPhrase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dialogus
        m_Dialogus = asset.FindActionMap("Dialogus", throwIfNotFound: true);
        m_Dialogus_NextPhrase = m_Dialogus.FindAction("NextPhrase", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dialogus
    private readonly InputActionMap m_Dialogus;
    private List<IDialogusActions> m_DialogusActionsCallbackInterfaces = new List<IDialogusActions>();
    private readonly InputAction m_Dialogus_NextPhrase;
    public struct DialogusActions
    {
        private @Controls m_Wrapper;
        public DialogusActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @NextPhrase => m_Wrapper.m_Dialogus_NextPhrase;
        public InputActionMap Get() { return m_Wrapper.m_Dialogus; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogusActions set) { return set.Get(); }
        public void AddCallbacks(IDialogusActions instance)
        {
            if (instance == null || m_Wrapper.m_DialogusActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DialogusActionsCallbackInterfaces.Add(instance);
            @NextPhrase.started += instance.OnNextPhrase;
            @NextPhrase.performed += instance.OnNextPhrase;
            @NextPhrase.canceled += instance.OnNextPhrase;
        }

        private void UnregisterCallbacks(IDialogusActions instance)
        {
            @NextPhrase.started -= instance.OnNextPhrase;
            @NextPhrase.performed -= instance.OnNextPhrase;
            @NextPhrase.canceled -= instance.OnNextPhrase;
        }

        public void RemoveCallbacks(IDialogusActions instance)
        {
            if (m_Wrapper.m_DialogusActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDialogusActions instance)
        {
            foreach (var item in m_Wrapper.m_DialogusActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DialogusActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DialogusActions @Dialogus => new DialogusActions(this);
    public interface IDialogusActions
    {
        void OnNextPhrase(InputAction.CallbackContext context);
    }
}
